// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouNaSchool.Wallet.Infrastructure.Persistence;

#nullable disable

namespace YouNaSchool.Wallet.Infrastructure.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    partial class WalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "Wallets");
                });

            modelBuilder.Entity("YouNaSchool.Wallet.Domain.Entities.WalletLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletLedgerEntries", "Wallets");
                });

            modelBuilder.Entity("YouNaSchool.Wallet.Domain.Entities.WalletRecharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientPaymentToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentProvider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProviderReferenceId")
                        .IsUnique()
                        .HasFilter("[ProviderReferenceId] IS NOT NULL");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletRecharges", "Wallets");
                });

            modelBuilder.Entity("YouNaSchool.Wallet.Domain.Entities.Wallets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Wallets", "Wallets");
                });

            modelBuilder.Entity("YouNaSchool.Wallet.Domain.Entities.WalletLedgerEntry", b =>
                {
                    b.HasOne("YouNaSchool.Wallet.Domain.Entities.Wallets", "Wallet")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("SharedKernel.Domain.VALUE_OBJECTS.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("WalletLedgerEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("WalletLedgerEntryId");

                            b1.ToTable("WalletLedgerEntries", "Wallets");

                            b1.WithOwner()
                                .HasForeignKey("WalletLedgerEntryId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("YouNaSchool.Wallet.Domain.Entities.WalletRecharge", b =>
                {
                    b.HasOne("YouNaSchool.Wallet.Domain.Entities.Wallets", "Wallet")
                        .WithMany("Recharges")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("SharedKernel.Domain.VALUE_OBJECTS.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("WalletRechargeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.HasKey("WalletRechargeId");

                            b1.ToTable("WalletRecharges", "Wallets");

                            b1.WithOwner()
                                .HasForeignKey("WalletRechargeId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("YouNaSchool.Wallet.Domain.Entities.Wallets", b =>
                {
                    b.OwnsOne("SharedKernel.Domain.VALUE_OBJECTS.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("WalletsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BalanceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("BalanceCurrency");

                            b1.HasKey("WalletsId");

                            b1.ToTable("Wallets", "Wallets");

                            b1.WithOwner()
                                .HasForeignKey("WalletsId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();
                });

            modelBuilder.Entity("YouNaSchool.Wallet.Domain.Entities.Wallets", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("Recharges");
                });
#pragma warning restore 612, 618
        }
    }
}
